var BLACK=0,WHITE=1,KING=0,QUEEN=1,ROOK=2,BISHOP=3,KNIGHT=4,PAWN=5,COLOR_NAMES=["Black","White"],PIECE_NAMES="King Queen Rook Bishop Knight Pawn".split(" "),PIECE_ALG="K Q R B N ".split(" "),MATERIAL=[0,100,50,30,30,10],LETTERS="abcdefgh",KING_MOVES=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],KNIGHT_MOVES=[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]],MATE=999999999,INFINITY=MATE+1,DRAW=0,HUMAN=0,COMPUTER=1,NS_SVG="http://www.w3.org/2000/svg",NS_XLINK="http://www.w3.org/1999/xlink";function Piece(a,b){this.color=a;this.piece=b}
var game={colorToPlay:WHITE,canCastleKingSide:[!0,!0],canCastleQueenSide:[!0,!0],board:[[new Piece(WHITE,ROOK),new Piece(WHITE,KNIGHT),new Piece(WHITE,BISHOP),new Piece(WHITE,QUEEN),new Piece(WHITE,KING),new Piece(WHITE,BISHOP),new Piece(WHITE,KNIGHT),new Piece(WHITE,ROOK)],[new Piece(WHITE,PAWN),new Piece(WHITE,PAWN),new Piece(WHITE,PAWN),new Piece(WHITE,PAWN),new Piece(WHITE,PAWN),new Piece(WHITE,PAWN),new Piece(WHITE,PAWN),new Piece(WHITE,PAWN)],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,
0,0],[0,0,0,0,0,0,0,0],[new Piece(BLACK,PAWN),new Piece(BLACK,PAWN),new Piece(BLACK,PAWN),new Piece(BLACK,PAWN),new Piece(BLACK,PAWN),new Piece(BLACK,PAWN),new Piece(BLACK,PAWN),new Piece(BLACK,PAWN)],[new Piece(BLACK,ROOK),new Piece(BLACK,KNIGHT),new Piece(BLACK,BISHOP),new Piece(BLACK,QUEEN),new Piece(BLACK,KING),new Piece(BLACK,BISHOP),new Piece(BLACK,KNIGHT),new Piece(BLACK,ROOK)]],kingRow:[7,0],kingCol:[4,4],twoPushCol:[-1,-1],history:[],players:[COMPUTER,HUMAN],options:{sound:!0,showLegalMoves:!0,
whiteOnTop:!1,negaMaxDepth:3,coefT:2,coefM:3}},_capture;function Move(a,b,c,d,e){this.piece=a;this.row1=d;this.col1=e;this.row2=b;this.col2=c}Move.prototype.toStr=function(){return this.castling===KING?"O-O":this.castling===QUEEN?"O-O-O":PIECE_ALG[this.piece]+LETTERS.charAt(this.col1)+String(this.row1+1)+(this.capture?"x":"-")+LETTERS.charAt(this.col2)+String(this.row2+1)+(this.enPassant?"ep":this.promote?PIECE_ALG[this.promote]:"")};Move.prototype.Capture=function(a){this.capture=a;return this};
Move.prototype.Castling=function(a){this.castling=a;return this};Move.prototype.EnPassant=function(){this.enPassant=!0;return this};Move.prototype.Promote=function(a){this.promote=a;return this};function getLegalMoves(a){return removeIllegalMoves(getPseudoLegalMoves(a),a)}function getPseudoLegalMoves(a){for(var b=[],c=0;8>c;c++)for(var d=0;8>d;d++)b=b.concat(getMovesForTile(a,c,d));return b}
function removeIllegalMoves(a,b){for(var c=[],d=0;d<a.length;d++)play(a[d]),isCheck(b)||c.push(a[d]),unplay(a[d]);return c}
function getMovesForTile(a,b,c){if(!game.board[b][c]||game.board[b][c].color!=a)return[];switch(game.board[b][c].piece){case PAWN:return getMovesForPawn(a,b,c);case ROOK:return getMovesForRook(a,b,c,ROOK);case BISHOP:return getMovesForBishop(a,b,c,BISHOP);case KNIGHT:return getMovesForKnight(a,b,c);case KING:return getMovesForKing(a,b,c);case QUEEN:return getMovesForQueen(a,b,c)}}
function getMovesForPawn(a,b,c){var d,e,f,g;a===WHITE?(d=1,e=1===b,g=4===b,f=6===b):(d=-1,e=6===b,g=3===b,f=1===b);var h=[];isEmptyTile(b+d,c)&&(h.push(new Move(PAWN,b+d,c,b,c)),e&&!game.board[b+2*d][c]&&h.push(new Move(PAWN,b+2*d,c,b,c)));0<c&&(isCapturableTile(b+d,c-1,a)?h.push((new Move(PAWN,b+d,c-1,b,c)).Capture(_capture)):g&&game.twoPushCol[1-a]===c-1&&h.push((new Move(PAWN,b+d,c-1,b,c)).Capture(PAWN).EnPassant()));7>c&&(isCapturableTile(b+d,c+1,a)?h.push((new Move(PAWN,b+d,c+1,b,c)).Capture(_capture)):
g&&game.twoPushCol[1-a]===c+1&&h.push((new Move(PAWN,b+d,c+1,b,c)).Capture(PAWN).EnPassant()));if(f&&0<h.length){var k=[];h.forEach(function(a){for(var d=QUEEN;d<=KNIGHT;d++)k.push((new Move(PAWN,a.row2,a.col2,b,c)).Capture(a.capture).Promote(d))});return k}return h}
function getMovesForRook(a,b,c,d){var e=[],f;for(f=c-1;0<=f;f--)if(game.board[b][f]){isCapturableTile(b,f,a)&&e.push((new Move(d,b,f,b,c)).Capture(_capture));break}else e.push(new Move(d,b,f,b,c));for(f=c+1;8>f;f++)if(game.board[b][f]){isCapturableTile(b,f,a)&&e.push((new Move(d,b,f,b,c)).Capture(_capture));break}else e.push(new Move(d,b,f,b,c));for(f=b+1;8>f;f++)if(game.board[f][c]){isCapturableTile(f,c,a)&&e.push((new Move(d,f,c,b,c)).Capture(_capture));break}else e.push(new Move(d,f,c,b,c));for(f=
b-1;0<=f;f--)if(game.board[f][c]){isCapturableTile(f,c,a)&&e.push((new Move(d,f,c,b,c)).Capture(_capture));break}else e.push(new Move(d,f,c,b,c));return e}
function getMovesForBishop(a,b,c,d){var e=[],f,g;f=b+1;for(g=c+1;8>f&&8>g;){if(game.board[f][g]){isCapturableTile(f,g,a)&&e.push((new Move(d,f,g,b,c)).Capture(_capture));break}else e.push(new Move(d,f,g,b,c));f++;g++}f=b+1;for(g=c-1;8>f&&0<=g;){if(game.board[f][g]){isCapturableTile(f,g,a)&&e.push((new Move(d,f,g,b,c)).Capture(_capture));break}else e.push(new Move(d,f,g,b,c));f++;g--}f=b-1;for(g=c-1;0<=f&&0<=g;){if(game.board[f][g]){isCapturableTile(f,g,a)&&e.push((new Move(d,f,g,b,c)).Capture(_capture));
break}else e.push(new Move(d,f,g,b,c));f--;g--}f=b-1;for(g=c+1;0<=f&&8>g;){if(game.board[f][g]){isCapturableTile(f,g,a)&&e.push((new Move(d,f,g,b,c)).Capture(_capture));break}else e.push(new Move(d,f,g,b,c));f--;g++}return e}
function getMovesForKnight(a,b,c){for(var d=[],e=0;e<KNIGHT_MOVES.length;e++)isEmptyTile(b+KNIGHT_MOVES[e][0],c+KNIGHT_MOVES[e][1])?d.push(new Move(KNIGHT,b+KNIGHT_MOVES[e][0],c+KNIGHT_MOVES[e][1],b,c)):isCapturableTile(b+KNIGHT_MOVES[e][0],c+KNIGHT_MOVES[e][1],a)&&d.push((new Move(KNIGHT,b+KNIGHT_MOVES[e][0],c+KNIGHT_MOVES[e][1],b,c)).Capture(_capture));return d}
function getMovesForKing(a,b,c){for(var d=[],e=0;e<KING_MOVES.length;e++)isEmptyTile(b+KING_MOVES[e][0],c+KING_MOVES[e][1])?d.push(new Move(KING,b+KING_MOVES[e][0],c+KING_MOVES[e][1],b,c)):isCapturableTile(b+KING_MOVES[e][0],c+KING_MOVES[e][1],a)&&d.push((new Move(KING,b+KING_MOVES[e][0],c+KING_MOVES[e][1],b,c)).Capture(_capture));game.canCastleKingSide[a]&&(game.board[b][5]||game.board[b][6]||game.board[b][7]&&game.board[b][7].piece===ROOK&&game.board[b][7].color===a&&(isAttackedTile(b,4,a)||isAttackedTile(b,
5,a)||isAttackedTile(b,6,a)||d.push((new Move(KING,b,6,b,4)).Castling(KING))));game.canCastleQueenSide[a]&&(game.board[b][3]||game.board[b][2]||game.board[b][1]||game.board[b][0]&&game.board[b][0].piece===ROOK&&game.board[b][0].color===a&&(isAttackedTile(b,4,a)||isAttackedTile(b,3,a)||isAttackedTile(b,2,a)||d.push((new Move(KING,b,2,b,4)).Castling(QUEEN))));return d}function getMovesForQueen(a,b,c){return getMovesForRook(a,b,c,QUEEN).concat(getMovesForBishop(a,b,c,QUEEN))}
function isEmptyTile(a,b){return 0>a||0>b||7<a||7<b?!1:!game.board[a][b]}function isCapturableTile(a,b,c){if(0>a||0>b||7<a||7<b||!game.board[a][b]||game.board[a][b].color===c||game.board[a][b].piece===KING)return!1;_capture=game.board[a][b].piece;return!0}
function isAttackedTile(a,b,c){var d,e;d=a+1;for(e=b+1;8>d&&8>e;){if(game.board[d][e]){if(isAttackableTile(d,e,c)){if(_capture===BISHOP)return!0;if(_capture===PAWN){if(d===a+1&&c===WHITE)return!0}else if(_capture===KING){if(d===a+1)return!0}else if(_capture===QUEEN)return!0}break}d++;e++}d=a+1;for(e=b-1;8>d&&0<=e;){if(game.board[d][e]){if(isAttackableTile(d,e,c)){if(_capture===BISHOP)return!0;if(_capture===PAWN){if(d===a+1&&c===WHITE)return!0}else if(_capture===KING){if(d===a+1)return!0}else if(_capture===
QUEEN)return!0}break}d++;e--}d=a-1;for(e=b-1;0<=d&&0<=e;){if(game.board[d][e]){if(isAttackableTile(d,e,c)){if(_capture===BISHOP)return!0;if(_capture===PAWN){if(d===a-1&&c===BLACK)return!0}else if(_capture===KING){if(d===a-1)return!0}else if(_capture===QUEEN)return!0}break}d--;e--}d=a-1;for(e=b+1;0<=d&&8>e;){if(game.board[d][e]){if(isAttackableTile(d,e,c)){if(_capture===BISHOP)return!0;if(_capture===PAWN){if(d===a-1&&c===BLACK)return!0}else if(_capture===KING){if(d===a-1)return!0}else if(_capture===
QUEEN)return!0}break}d--;e++}for(e=b-1;0<=e;e--)if(game.board[a][e]){if(isAttackableTile(a,e,c)){if(_capture===ROOK)return!0;if(_capture===KING){if(e===b-1)return!0}else if(_capture===QUEEN)return!0}break}for(e=b+1;8>e;e++)if(game.board[a][e]){if(isAttackableTile(a,e,c)){if(_capture===ROOK)return!0;if(_capture===KING){if(e===b+1)return!0}else if(_capture===QUEEN)return!0}break}for(d=a+1;8>d;d++)if(game.board[d][b]){if(isAttackableTile(d,b,c)){if(_capture===ROOK)return!0;if(_capture===KING){if(d===
a+1)return!0}else if(_capture===QUEEN)return!0}break}for(d=a-1;0<=d;d--)if(game.board[d][b]){if(isAttackableTile(d,b,c)){if(_capture===ROOK)return!0;if(_capture===KING){if(d===a-1)return!0}else if(_capture===QUEEN)return!0}break}for(d=0;d<KNIGHT_MOVES.length;d++)if(isCapturableTile(a+KNIGHT_MOVES[d][0],b+KNIGHT_MOVES[d][1],c)&&_capture===KNIGHT)return!0;return!1}function isAttackableTile(a,b,c){if(game.board[a][b].color===c)return!1;_capture=game.board[a][b].piece;return!0}
function isCheck(a){return isAttackedTile(game.kingRow[a],game.kingCol[a],a)}function getLegalMove(a,b,c,d,e){a=removeIllegalMoves(getMovesForTile(game.colorToPlay,a,b),game.colorToPlay);for(b=0;b<a.length;b++)if(a[b].row2===c&&a[b].col2===d&&a[b].promote==e)return a[b]}
function play(a){var b=game.board[a.row1][a.col1].color;game.board[a.row2][a.col2]=game.board[a.row1][a.col1];game.board[a.row1][a.col1]=0;a.enPassant?game.board[b===WHITE?4:3][a.col2]=0:a.castling===KING?(game.board[a.row1][5]=game.board[a.row1][7],game.board[a.row1][7]=0):a.castling===QUEEN?(game.board[a.row1][3]=game.board[a.row1][0],game.board[a.row1][0]=0):a.promote&&(game.board[a.row2][a.col2].piece=a.promote);a.twoPushColWas=game.twoPushCol[b];game.twoPushCol[b]=a.piece===PAWN&&(1===a.row1&&
3===a.row2||6===a.row1&&4===a.row2)?a.col1:-1;game.twoPushCol[1-b]=-1;a.piece===KING&&(game.kingRow[b]=a.row2,game.kingCol[b]=a.col2);game.canCastleKingSide[b]&&(a.piece===KING||a.piece===ROOK&&7===a.col1)&&(game.canCastleKingSide[b]=!1,a.preventsCastleKingSide=!0);game.canCastleQueenSide[b]&&(a.piece===KING||a.piece===ROOK&&0===a.col1)&&(game.canCastleQueenSide[b]=!1,a.preventsCastleQueenSide=!0);game.colorToPlay=1-game.colorToPlay;game.history.push(a)}
function unplay(a){var b=game.board[a.row2][a.col2].color;game.board[a.row1][a.col1]=game.board[a.row2][a.col2];void 0===a.capture?game.board[a.row2][a.col2]=0:a.enPassant?(game.board[a.row2][a.col2]=0,game.board[b===WHITE?4:3][a.col2]=new Piece(1-b,PAWN)):game.board[a.row2][a.col2]=new Piece(1-b,a.capture);a.promote&&(game.board[a.row1][a.col1].piece=PAWN);a.piece===KING&&(a.castling===KING?(game.board[a.row1][7]=game.board[a.row1][5],game.board[a.row1][5]=0):a.castling===QUEEN&&(game.board[a.row1][0]=
game.board[a.row1][3],game.board[a.row1][3]=0),game.kingRow[b]=a.row1,game.kingCol[b]=a.col1);game.twoPushCol[b]=a.twoPushColWas;a.preventsCastleKingSide&&(game.canCastleKingSide[b]=!0);a.preventsCastleQueenSide&&(game.canCastleQueenSide[b]=!0);game.colorToPlay=1-game.colorToPlay;game.history.pop()}function restart(){for(;0<game.history.length;)unplay(game.history[game.history.length-1])}
function logBoard(){console.log("Board ("+COLOR_NAMES[game.colorToPlay]+" to play)");for(var a="",b=7;0<=b;b--){for(var c=0;8>c;c++)a=0===game.board[b][c]?a+"-":game.board[b][c].piece===PAWN?a+(game.board[b][c].color===WHITE?"P":"p"):game.board[b][c].color===BLACK?a+PIECE_ALG[game.board[b][c].piece].toLowerCase():a+PIECE_ALG[game.board[b][c].piece];a+="\n"}console.log(a)}
function logHistory(){console.log("Moves history ("+game.history.length+")");for(var a=0,b=1;a<game.history.length;a+=2,b++)console.log(b+": "+game.history[a].toStr()+(a+1<game.history.length?"\t"+game.history[a+1].toStr():""))}function logLegalMoves(){var a=getLegalMoves(game.colorToPlay);console.log("Legal moves for "+COLOR_NAMES[game.colorToPlay]+" ("+a.length+")");a.forEach(function(a){console.log(a.toStr())})}
function logEval(){console.log("Evaluation for "+COLOR_NAMES[game.colorToPlay]+": "+evaluate())}function evaluate(){var a=game.colorToPlay,b=getLegalMoves(a).length;if(0===b)return isCheck(a)?-MATE:DRAW;b-=getLegalMoves(1-a).length;a=evalMaterial(a);return game.options.coefT*b+game.options.coefM*a}function evalMaterial(a){for(var b=0,c=0;8>c;c++)for(var d=0;8>d;d++){var e=game.board[c][d];e&&(b+=MATERIAL[e.piece]*(e.color===a?1:-1))}return b}
function negaMax(a,b,c){if(0===a)return{score:evaluate(),moves:[]};var d=getLegalMoves(game.colorToPlay);if(0===d.length)return{score:evaluate(),moves:[]};for(var e=-INFINITY,f=[],g=0;g<d.length;g++){play(d[g]);var h=negaMax(a-1,-c,-b),k=-h.score;unplay(d[g]);k>e&&(e=k,f=h.moves.slice(),f.unshift(d[g]));b=Math.max(b,k);if(b>=c)break}return{score:e,moves:f}}
function logBestMove(){var a=new Date,b=negaMax(game.options.negaMaxDepth,-INFINITY,+INFINITY),c=new Date,d=[];b.moves.forEach(function(a){d.push(a.toStr())});console.log("NegaMax("+game.options.negaMaxDepth+"): "+b.score+" ["+d.join(", ")+"]");console.log("I thought for "+(c-a)+"ms")}function getBestMove(){var a=negaMax(game.options.negaMaxDepth,-INFINITY,+INFINITY);if(a.moves.length)return a.moves[0]};var audioGood=new Audio("sound/Applause.mp3"),audioBad=new Audio("sound/Buzzer.mp3"),computerBeep=new Audio("sound/tone-beep.wav"),$=document.getElementById.bind(document),gTiles=$("tiles"),gHighlights=$("highlights"),gPieces=$("pieces"),selection={tile1:null,piece1:null,classBefore1:"",tile2:null,piece2:null,classBefore2:"",promote:null},tileA1=$("a1");function tileId(a,b){return LETTERS.charAt(b)+String(a+1)}
function addTilesEventListener(){for(var a,b=0;8>b;b++)for(var c=0;8>c;c++)a=$(tileId(b,c)),a.addEventListener("click",tileClicked)}
function drawPiece(a,b,c){var d=document.createElementNS(NS_SVG,"image");d.setAttributeNS(NS_XLINK,"xlink:href","img/"+PIECE_NAMES[a.piece]+"_"+COLOR_NAMES[a.color]+".svg");d.setAttribute("x",12.5*c+"%");d.setAttribute("y",12.5*(7-b)+"%");d.setAttribute("width","12.5%");d.setAttribute("height","12.5%");d.setAttribute("data-color",a.color);d.setAttribute("data-row",b);d.setAttribute("data-col",c);d.setAttribute("class","piece "+PIECE_NAMES[a.piece]);d.addEventListener("click",pieceClicked);gPieces.appendChild(d);
$(tileId(b,c)).removeEventListener("click",tileClicked)}function drawPieces(){for(var a=0;8>a;a++)for(var b=0;8>b;b++)game.board[a][b]&&drawPiece(game.board[a][b],a,b);game.options.whiteOnTop&&updateTransform()}function tileClicked(a){selectTile(a.target)}function pieceClicked(a){selectTile(getTileFromPiece(a.target),a.target)}function getTileFromPiece(a){return $(tileId(parseInt(a.getAttribute("data-row")),parseInt(a.getAttribute("data-col"))))}
function selectTile(a,b){if(game.players[game.colorToPlay]!==COMPUTER)if(a==selection.tile1)resetSelection();else if(void 0!=b&&parseInt(b.getAttribute("data-color"))==game.colorToPlay)resetSelection(),selection.tile1=a,selection.piece1=b,selection.classBefore1=a.getAttribute("class"),a.setAttribute("class",selection.classBefore1+" tile-selected"),game.options.showLegalMoves&&showLegalMovesForTile(a);else if(null!=selection.tile1){selection.tile2=a;selection.piece2=b;selection.classBefore2=a.getAttribute("class");
a.setAttribute("class",selection.classBefore2+" tile2-selected");if(selection.piece1.getAttribute("class")=="piece "+PIECE_NAMES[PAWN]){if("0"==a.getAttribute("data-row")){promotionPopup(BLACK);return}if("7"==a.getAttribute("data-row")){promotionPopup(WHITE);return}}var c=checkMove();c?playMove(c):resetSelection()}}
function resetSelection(){hideLegalMoves();selection.tile1&&(selection.tile1.setAttribute("class",selection.classBefore1),selection.tile1=null,selection.piece1=null,selection.classBefore1="",selection.tile2&&(selection.tile2.setAttribute("class",selection.classBefore2),selection.tile2=null,selection.piece2=null,selection.classBefore2="",selection.promote=null))}
function checkMove(){var a=getLegalMove(parseInt(selection.tile1.getAttribute("data-row")),parseInt(selection.tile1.getAttribute("data-col")),parseInt(selection.tile2.getAttribute("data-row")),parseInt(selection.tile2.getAttribute("data-col")),selection.promote);game.options.sound&&(a?audioGood.play():audioBad.play());return a}
function playMove(a){selection.piece2&&gPieces.removeChild(selection.piece2);selection.piece1.setAttribute("x",12.5*a.col2+"%");selection.piece1.setAttribute("y",12.5*(7-a.row2)+"%");selection.piece1.setAttribute("data-row",a.row2);selection.piece1.setAttribute("data-col",a.col2);var b,c;game.options.whiteOnTop&&(b=selection.piece1.width.baseVal.value,c=selection.piece1.height.baseVal.value,selection.piece1.setAttribute("transform","translate("+(2*a.col2+1)*b+" "+(2*(7-a.row2)+1)*c+") rotate(180)"));
if(a.enPassant)b=getPieceAt(PAWN,game.colorToPlay==WHITE?4:3,a.col2),getTileFromPiece(b).addEventListener("click",tileClicked),gPieces.removeChild(b);else if(a.castling==KING){var d=getPieceAt(ROOK,a.row1,7);getTileFromPiece(d).addEventListener("click",tileClicked);d.setAttribute("x","62.5%");d.setAttribute("data-col",5);getTileFromPiece(d).removeEventListener("click",tileClicked);game.options.whiteOnTop&&d.setAttribute("transform","translate("+11*b+" "+(2*(7-a.row1)+1)*c+") rotate(180)")}else a.castling==
QUEEN?(d=getPieceAt(ROOK,a.row1,0),getTileFromPiece(d).addEventListener("click",tileClicked),d.setAttribute("x","37.5%"),d.setAttribute("data-col",3),getTileFromPiece(d).removeEventListener("click",tileClicked),game.options.whiteOnTop&&d.setAttribute("transform","translate("+7*b+" "+(2*(7-a.row1)+1)*c+") rotate(180)")):a.promote&&(selection.piece1.setAttributeNS(NS_XLINK,"xlink:href","img/"+PIECE_NAMES[a.promote]+"_"+COLOR_NAMES[game.colorToPlay]+".svg"),selection.piece1.setAttribute("class","piece "+
PIECE_NAMES[a.promote]));play(a);updateColorToPlay();selection.tile1.addEventListener("click",tileClicked);selection.tile2.removeEventListener("click",tileClicked);resetSelection();game.players[game.colorToPlay]===COMPUTER&&($("thinking").innerHTML="Let me think about it !",$("thinking").style.visibility="visible",setTimeout(computerPlay,100))}
function computerPlay(){var a=getBestMove();a?(play(a),redrawBoard(),updateColorToPlay(),game.options.sound&&computerBeep.play(),selection.tile1=$(tileId(a.row1,a.col1)),selection.tile2=$(tileId(a.row2,a.col2)),selection.classBefore1=selection.tile1.getAttribute("class"),selection.classBefore2=selection.tile2.getAttribute("class"),selection.tile1.setAttribute("class",selection.classBefore1+" tile-selected"),selection.tile2.setAttribute("class",selection.classBefore2+" tile2-selected"),$("thinking").innerHTML=
a.toStr(),setTimeout(resetSelection,800),0===getLegalMoves(game.colorToPlay).length&&($("thinking").style.visibility="hidden",setPopupVisible("lose",!0))):($("thinking").style.visibility="hidden",setPopupVisible("win",!0))}function getPieceAt(a,b,c){a=getElemByClass(gPieces,PIECE_NAMES[a]);for(var d=0;d<a.length;d++)if(a.item(d).getAttribute("data-col")==c&&a.item(d).getAttribute("data-row")==b)return a.item(d)}
function getElemByClass(a,b){return a.getElementsByClassName?a.getElementsByClassName(b):document.getElementsByClassName(b)}function toggleShowLegalMoves(){game.options.showLegalMoves=!game.options.showLegalMoves;$("toggleShowLegalMoves").setAttribute("class","token "+(game.options.showLegalMoves?"ON":"OFF"))}
function toggleSound(){game.options.sound&&(audioGood.pause(),audioBad.pause());game.options.sound=!game.options.sound;$("toggleSound").setAttribute("class","token "+(game.options.sound?"ON":"OFF"))}
function showLegalMovesForTile(a){a=removeIllegalMoves(getMovesForTile(game.colorToPlay,parseInt(a.getAttribute("data-row")),parseInt(a.getAttribute("data-col"))),game.colorToPlay);for(var b=0;b<a.length;b++){var c=document.createElementNS(NS_SVG,"circle");c.setAttribute("cx",String(12.5*a[b].col2+6.25)+"%");c.setAttribute("cy",String(12.5*(7-a[b].row2)+6.25)+"%");a[b].capture?(c.setAttribute("r","4%"),c.setAttribute("class","legal red")):(c.setAttribute("r","2%"),c.setAttribute("class","legal green"));
gHighlights.appendChild(c)}}function hideLegalMoves(){for(var a=getElemByClass(gHighlights,"legal");0<a.length;)gHighlights.removeChild(a.item(0))}
function rotateBoard(){var a=$("svg");game.options.whiteOnTop=!game.options.whiteOnTop;if(game.options.whiteOnTop)a.setAttribute("class","rotate180"),updateTransform(),window.addEventListener("resize",updateTransform),$("rotateBoard").setAttribute("class","token ON");else{window.removeEventListener("resize",updateTransform);a.setAttribute("class","");for(var a=gPieces.getElementsByTagName("*"),b=0;b<a.length;b++)a.item(b).removeAttribute("transform");$("rotateBoard").setAttribute("class","token OFF")}}
function updateTransform(){for(var a=tileA1.width.baseVal.value,b=tileA1.height.baseVal.value,c,d,e=gPieces.getElementsByTagName("*"),f=0;f<e.length;f++)c=parseInt(e.item(f).getAttribute("data-row")),d=parseInt(e.item(f).getAttribute("data-col")),e.item(f).setAttribute("transform","translate("+(2*d+1)*a+" "+(2*(7-c)+1)*b+") rotate(180)")}
function redrawBoard(){for(;gPieces.firstElementChild;)getTileFromPiece(gPieces.firstElementChild).addEventListener("click",tileClicked),gPieces.removeChild(gPieces.firstElementChild);drawPieces()}function unplayLastMove(){0!==game.history.length&&(unplay(game.history[game.history.length-1]),game.players[game.colorToPlay]===COMPUTER&&unplay(game.history[game.history.length-1]),redrawBoard(),updateColorToPlay())}
function restartGame(){0!==game.history.length&&(restart(),redrawBoard(),updateColorToPlay())}function updateColorToPlay(){$("colorToPlay").setAttribute("class","token "+COLOR_NAMES[game.colorToPlay])}function promotionPopup(a){$("prom_"+COLOR_NAMES[1-a]).style.visibility="hidden";$("prom_"+COLOR_NAMES[a]).style.visibility="visible";setPopupVisible("prom",!0)}
function initPromotionPopup(a){for(var b=$("prom_"+COLOR_NAMES[a]).getElementsByTagName("image"),c=0,d=QUEEN;4>c;c++,d++)b[c].setAttributeNS(NS_XLINK,"xlink:href","img/"+PIECE_NAMES[d]+"_"+COLOR_NAMES[a]+".svg"),b[c].setAttribute("data-piece",d),b[c].addEventListener("click",promotionPieceClicked)}function setPopupVisible(a,b){$(a).style.display=b?"initial":"none";$(a).style.pointerEvents=b?"auto":"none"}function cancelPromote(a){resetSelection();setPopupVisible("prom",!1);a.preventDefault()}
function promotionPieceClicked(a){selection.promote=parseInt(this.getAttribute("data-piece"));setPopupVisible("prom",!1);(a=checkMove())&&playMove(a)}function playAgain(a){setPopupVisible("win",!1);setPopupVisible("lose",!1);restartGame();a.preventDefault()}function unplayAfterLose(a){setPopupVisible("lose",!1);unplayLastMove();a.preventDefault()};audioGood.load();audioBad.load();computerBeep.load();addTilesEventListener();drawPieces();$("pan-side1").addEventListener("click",resetSelection);$("pan-side2").addEventListener("click",resetSelection);$("toggleShowLegalMoves").setAttribute("class","token "+(game.options.showLegalMoves?"ON":"OFF"));$("toggleSound").setAttribute("class","token "+(game.options.sound?"ON":"OFF"));$("rotateBoard").setAttribute("class","token "+(game.options.whiteOnTop?"ON":"OFF"));
$("toggleShowLegalMoves").addEventListener("click",toggleShowLegalMoves);$("toggleSound").addEventListener("click",toggleSound);$("rotateBoard").addEventListener("click",rotateBoard);$("logBoard").addEventListener("click",logBoard);$("logHistory").addEventListener("click",logHistory);$("logLegalMoves").addEventListener("click",logLegalMoves);$("logEval").addEventListener("click",logEval);$("logBestMove").addEventListener("click",logBestMove);$("redrawBoard").addEventListener("click",redrawBoard);
$("unplayLastMove").addEventListener("click",unplayLastMove);$("restartGame").addEventListener("click",restartGame);initPromotionPopup(BLACK);initPromotionPopup(WHITE);$("cancelPromote").addEventListener("click",cancelPromote);$("playAgain").addEventListener("click",playAgain);$("retry").addEventListener("click",playAgain);$("unplayAfterLose").addEventListener("click",unplayAfterLose);
